sudo: required
services:
  - docker
before_script:
  - docker-compose up -d

language: java
jdk:
  - oraclejdk8
script: mvn clean verify -Pupload-pacts,verify-pacts jacoco:report
cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn coveralls:report

after_script:
  - docker-compose down
